# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9059dc8423402e819e1253db0115f0f884bddd95777fd31d6444388d1b678d08129deb77301761aa53f6736e6174222bda523026bdaba9eda60df50d699b0b68

test:
  secret_key_base: ff85f33b7ce5ef5bf165a305ad8dd99e0081d3f5d7e46b435b38f536b2d1dd77966487fa45e8af93b83c41f245d3d0c772394d0a546b8f687d15a5969efe084c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
